export const addConnection = 'addConnection'
export const loadListConnection = 'loadListConnection'
export const showOrHideModal = 'showOrHideModal'
export const editConnection = 'editConnection'
export const resetState = 'resetState'
